### ISSUE TITLE
Release package compatible with Django 3.2

### ISSUE THREAD

**Issue by PetrDlouhy** [akarzim/image-sitemaps#7]
@akarzim Could you please also release the fix for Django 3.2 (#6) as PyPI package?

**Comment by akarzim** [comment]
Hi @PetrDlouhy,
I haven't used Django and PyPI for a long time. I'll be happy to promote you to co-owner of this repository and let you do the release :) What do you think?

**Comment by PetrDlouhy** [comment]
Hi @akarzim,

yes, that would be great. Thank you.

**Comment by PetrDlouhy** [comment]
@akarzim Can you please give me the right to PyPI, so I could make the new release? My username is `petr.dlouhy`.

**Comment by akarzim** [comment]
Sure ! It's done, enjoy :)

**Comment by PetrDlouhy** [comment]
@akazim Thank you very much. I would like also to keep this repository as base, could you give mi rights also here?

**Comment by akarzim** [comment]
your invitation had expired. I have just sent you another one 🚀

**Comment by PetrDlouhy** [comment]
@akarzim Thank you very much. Now all tests are passing and the new version is released. I had to release as `2.0.0` to avoid problems with `1.05` being interpreted as `1.5`.
